version: "3.9"

services:
  mariadb-master:
    container_name: mariadb-master
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - './db_master_data:/var/lib/mysql'
      - './master.cnf:/etc/mysql/conf.d/mysql.cnf'
    environment:
      MARIADB_ROOT_PASSWORD: 1 
    ports:
      - "3306:3306"
    networks:
      - db-stack

  mariadb-slave:
    container_name: mariadb-slave
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - './db_slave_data:/var/lib/mysql'
      - './slave.cnf:/etc/mysql/conf.d/mysql.cnf'
    environment:
      MARIADB_ROOT_PASSWORD: 1 
    ports:
      - "3307:3306"
    networks:
      - db-stack

  mariadb-slave2:
    container_name: mariadb-slave2
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - './db_slave2_data:/var/lib/mysql'
      - './slave2.cnf:/etc/mysql/conf.d/mysql.cnf'
    environment:
      MARIADB_ROOT_PASSWORD: 1
    ports:
      - "3308:3306"
    networks:
      - db-stack

networks:
  db-stack:
    name: db-stack
    external: true

volumes:
  db_master_data:
  db_slave_data:
  db_slave2_data:  
